### PR TITLE
Create polaris_engineering.json

### PR DESCRIPTION
**Pull request by GuidoPenta**
Hi,
I'd like to insert a new company to the list. Thank you!

### CODE REVIEW

**Review by edoardocostantinidev — COMMENTED** [review]
Hi @GuidoPenta, thank you for your submission. Is there any piece of evidence that actually mentions remote working on those sites you linked? I couldn't find any.

**Comment by GuidoPenta** [comment]
Hello @edoardocostantinidev ! That company is actually my client (and will be my future company), so it's 100% assured the full remote approach for devs :)

**Review by edoardocostantinidev — APPROVED** [review]

**Comment by alessandromr** [comment]
Pardon the delays @GuidoPenta

**Comment by GuidoPenta** [comment]
No prob, thank you!

**Pull request merged**
