### PR TITLE
Update flowing.json

### PR DESCRIPTION
**Pull request by baldarn**
updated flowing hiring policies

cit:

```
Non ci sono posizioni aperte che rispecchiano le tue skill? 
Preferisci collaborare con noi in qualità di freelance? 
Pensi di essere la persona giusta per Flowing? 
```

### CODE REVIEW

**Comment by alessandromr** [comment]
@baldarn indeed that should be possible. I will change the parameter to an array.
Will update you on the PR as soon as it's done

**Comment by alessandromr** [comment]
Hey @baldarn, sorry for the delay. You can now add multiple hiring policies. You can find the format in the conflicts or also here:
```
 "hiring_policies": [
    "Direct"
  ],
```

**Comment by baldarn** [comment]
updated code ;)

**Comment by baldarn** [comment]
after the merge the hiring policy is of arrays is empty.. ?

**Pull request merged**
