### PR TITLE
Update URL for TUI Musement

### PR DESCRIPTION
**Pull request by hpatoio**
Update URL for TUI Musement to https://www.tuimusement.com/ as requested by our SEO manager

### CODE REVIEW

**Review by alessandromr — APPROVED** [review]

**Review by alessandromr — CHANGES_REQUESTED** [review]
Hi @hpatoio could you please edit the source file as described on https://github.com/italiaremote/awesome-italia-remote/blob/main/CONTRIBUTING.md 

README will be changed automatically and must be kept untouched.

Thanks

**Comment by hpatoio** [comment]
Fix pushed. I've also update info about hiring policies.

**Comment by hpatoio** [comment]
Bump.

@alessandromr @edoardocostantinidev

**Comment by edoardocostantinidev** [comment]
sorry for the late reply @hpatoio 🙏🏻 looking into it

**Review by alessandromr — APPROVED** [review]

**Comment by hpatoio** [comment]
@alessandromr and @edoardocostantinidev  I still see the wrong URL here https://github.com/italiaremote/awesome-italia-remote

Not sure how the update of the README works but [I don't see any update](https://github.com/italiaremote/awesome-italia-remote/commits/main/README.md) after this MR was merged.

Anything I can do ?

**Pull request merged**
