### PR TITLE
Create sqlite_cloud.json

### PR DESCRIPTION
**Pull request by marcobambini**

### CODE REVIEW

**Review by edoardocostantinidev — COMMENTED** [review]
Hi @marcobambini can't seem to find links or posts that mention full remote policies. Care to elaborate how you know this company is full remote? (e.g. you work there/it's your company, etc.)

**Comment by marcobambini** [comment]
@edoardocostantinidev it is my company, I am the founder and CEO.

**Review by edoardocostantinidev — APPROVED** [review]

**Comment by edoardocostantinidev** [comment]
thanks for the contribution @marcobambini !

**Comment by marcobambini** [comment]
Thanks for the creation of this very useful repo @edoardocostantinidev!

**Pull request merged**
