### PR TITLE
Added Dove.it to remote software company list

### PR DESCRIPTION
**Pull request by salvatore-vadacca**
It should add Dove.it as a remote-first software company.

### CODE REVIEW

**Comment by edoardocostantinidev** [comment]
Hi @salvatore-vadacca, I don't see any dev/cloud position available at dove.it. If you can supply any other piece of info we sure will merge this PR.

**Review by edoardocostantinidev — CHANGES_REQUESTED** [review]
no software remote position available, cannot verify stack

**Comment by salvatore-vadacca** [comment]
Hi @edoardocostantinidev. Thanks for the feedback.

I don't get what is the purpose of this list. If you are going to list only companies with open job vacancies, it is no longer our case since we have just closed positions for junior and senior software engineers. Hopefully we will grow and we will hire more people in the months.

If instead you just need something to verify our tech stack, here the link to the just closed positions on LinkedIn: https://www.linkedin.com/jobs/view/2896373347/ and https://www.linkedin.com/jobs/view/2896352450/

**Comment by edoardocostantinidev** [comment]
@salvatore-vadacca Thanks for the quick reply. The purpose of this list is to gather fully remote companies that hire in Italy so that people don't have to scout linkedin, etc., for hours. The job posts you have provided validate everything you stated so I'm approving this PR! Thanks for your submission.

**Review by edoardocostantinidev — APPROVED** [review]

**Comment by salvatore-vadacca** [comment]
Thanks for the explanation. Cheers!

**Pull request merged**
